etc/flowforge-storage.yml
forge/config.js
forge/drivers/localfs.js

Ben, some necessary changes for testing nr-file-nodes

Fix up for testing

---

forge/drivers/s3.js

Better fix for s3 append

---

forge/auth.js

Fix Authentication

---

forge/auth.js
index.js
test/unit/auth_spec.js
test/unit/drivers/setup.js
test/unit/drivers/vfs_spec.js
test/unit/setup.js

fixes  https://github.com/flowforge/security/issues/11
Also, adds tests to confirm issue is resolved.
Details deliberately left out s- please contact me if there are difficulties understanding something when reviewing

Fix token issue

---

forge/context-driver/redis.js

Fix deletion of redis context

---

forge/context-driver/redis.js

[ensure object is not null before trying to assign to nothing](https://github.com/flowforge/flowforge-file-server/commit/063e62fb00b042580b76596ec5b4bac5db3e36e6)
[In `set`, delete nested instead values of setting `undefined`](https://github.com/flowforge/flowforge-file-server/commit/8217666c797460daf726336a7791b91fb55316cd)
[ensure recursive assignment scope is maintained (dont allow it to creep  outside of scope)](https://github.com/flowforge/flowforge-file-server/commit/4aee6a277873c44954f8c31988f90fd0a52b59d9)
[in `get()`, get values 1 by 1 to avoid an exception when one key of the paths does not exist in redis](https://github.com/flowforge/flowforge-file-server/commit/4544f93b3f3e59b65c372b38694d819c5522ddd6)

Handle undefined values and multiple keys in redis context driver

---

README.md
etc/flowforge-storage.yml
forge/context-driver/memory.js
forge/context-driver/postgres.js
forge/context-driver/redis.js
forge/routes/context.js
forge/routes/index.js
package.json

Adds Persistent
Comes with 2 drivers at the moment
- memory for testing
- Redis

Persistent Context support

---

README.md
forge/context-driver/memory.js

Remove console logging context mem & update docs

---

package.json

Add sqlite to package.json

---

test/unit/routes/context_spec.js

Add conditional test for enable/disable postgres tests

---

forge/drivers/s3.js

Only count files if there are files

S3 quota check

---

forge/auth.js
forge/config.js
forge/drivers/memory.js
forge/routes/quota.js

Fix linting

---

.github/workflows/build.yml
.gitignore
package-lock.json

See https://github.com/flowforge/flowforge-dev-env/issues/20

Add package-lock.json

---

forge/auth.js
forge/context-driver/sequelize.js
forge/routes/context.js
forge/routes/files.js
test/unit/setup.js

part of #66 
Allows quota values to be passed from the Forge App.
It gets the quota sizes for the team when it checks the token passed.
#66

First pass at variable quotas

---

package-lock.json
package.json

Trying to remove all the CVE dependencies for Vanta

Bump nodemon to allow other deps to be updated

---

package-lock.json
package.json

Update dependencies to clear CVEs

---

package-lock.json
package.json

Making sure semver gets updated to a safe version

Bump the semver dep

---

README.md
etc/flowforge-storage.yml
forge/auth.js
forge/fileServer.js
package-lock.json
package.json

Adds a `/metrics` endpoint if enabled.
#85

Add /metrics endpoint

---

.github/workflows/publish.yml

Bump workflows to v0.1.1 version .

Bump workflows to v0.1.1 version

---

package-lock.json
package.json

Part of https://github.com/FlowFuse/admin/issues/211
Updates to `@flowfuse` npm org name

Update npm org name

---

.github/workflows/release-build.yml

Update npm-publish action version to v2
[#2029](https://github.com/FlowFuse/flowfuse/issues/2029)

Update npm-publish action version to v2

---

forge/auth.js
forge/fileServer.js
package-lock.json
package.json

This PR adds a `/health` endpoint for monitoring purposes when the application is running in a container. 
https://github.com/FlowFuse/helm/issues/266
https://github.com/FlowFuse/helm/issues/263

Feat: Add health check enpoint

---

CHANGELOG.md
package-lock.json
package.json

Bump for 2.6.1

---

forge/auth.js

fixes FlowFuse/flowfuse#4431
Not parsing response to a JSON object
FlowFuse/flowfuse#4431

Fix quota parsing

---

forge/auth.js
forge/context-driver/sequelize.js
forge/drivers/localfs.js
index.js

Adds logging around quota checks so we can get better insight into 413 responses.

Add logging on context quota calcs
